---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
formatter:
  rubocop:
    cops: all
    except: []
    only: []
    extra_args: []
require_paths:
  - lib
  - "spec/contexts"
  - bin

plugins: []
max_files: 5000
